appId: com.storehub.kiosk.test
tags:
  - Settings
  - smoke
---
- tapOn: "Tap to begin your order!"
- tapOn: "⚙️ Settings"
- tapOn: "1"
- tapOn: "1"
- tapOn: "1"
- tapOn: "1"
- tapOn: "al_btn_260"
- tapOn:
    id: "al_btn_110"
    index: 0
- assertVisible: "Shift Management"
- tapOn:
    id: "al_btn_110"
    index: 1
- tapOn: "al_kiosk_sync_start"
- assertVisible: "100"
- tapOn:
    id: "al_btn_110"
    index: 2
- assertVisible: "Z-Readings"
- assertVisible: "Close Z-Reading"
- tapOn:
    id: "al_btn_440"
- assertVisible: "Print Z-Reading"
- tapOn:
    id: "al_btn_46"
- assertVisible: "Print Z-Reading"
- tapOn:
    id: "al_btn_180"
- tapOn:
    id: "al_btn_110"
    index: 3
- assertVisible:
    text: "Session Timeout"
    index: 1
- tapOn:
    id: "al_btn_110"
    index: 4
- assertVisible: "Printer Management"
- assertVisible: "Search Printer"
- assertVisible: "Print Test Receipt"
- tapOn:
    id: "al_search_printer"
- assertVisible: "Searching for Printers"
- assertVisible: "Sorry, there are no printers found. Do you still want to connect to a printer?"
- assertVisible: "al_modalinfo_cancel"
- tapOn: "al_modalinfo_cancel"
- tapOn:
    id: "al_btn_933"
- tapOn:
    id: "al_btn_941"
